tugaslab:-nl,
write('berikan titik sebagai end of line setiap mengisi'),nl,nl,
write('1. Biodata'),nl,
write('2. Luas Persegi Panjang'),nl,
write('3. Keliling Persegi Panjang'),nl,
write('4. Exit'),nl,nl,
write('pilih:'),read(Pilihan),nl,
( Pilihan = 1,
  write('**BIODATA**'),nl,nl,
  write('Masukkan Nama   :'),read(A),
  write('Masukkan NPM    :'),read(B),
  write('Masukkan Prodi  :'),read(C),
  write('Masukkan Hobby   :'),read(D),nl,
  write('Selamat datang ngab '),write(A),nl,
  write('NPM: '), write(B),nl,
  write('Prodi: '), write(C),nl,
  write('Hobby: '),write(D),nl,nl,
  tugaslab;
  Pilihan = 2,
  write('**Luas Persegi Panjang**'), nl,nl,
  write('Panjang:'),read(P),
  write('Lebar  :'),read(L),nl,nl,
  S is P*L,
  write('Luas Persegi Panjangnya adalah:'), write(S),nl,
  tugaslab;
  Pilihan = 3,
  write('**Keliling Persegi Panjang**'),nl,nl,
  write('Panjang:'),read(G),
  write('Lebar :'),read(E),nl,nl,
  K is 2*(G+E),
  write('Keliling adalah :'), write(K),
  tugaslab;
  Pilihan= 4,
  write('nuhuns')).